#!/usr/bin/env bash

function main {
  local shome="${_openresty_home:-"$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"}"
  source "$shome/script/profile"

  if [[ "$#" == 0 ]]; then
    set -- default
  fi

  case "${1:-}" in
    default)
      case "$(uname -s)" in
        Linux)
          export LD_LIBRARY_PATH="/opt/pkgsrc/install/lib"
          ;;
      esac
      nginx -p "$shome" -c "$shome/nginx.conf" -g "daemon off;"
      ;;
    *)
      echo "ERROR: unknown server command: ${1:-/not-supplied/}" 1>&2
      return 1
      ;;
  esac
}

main "$@"

